### ISSUE TITLE
yarn install 에러

### ISSUE THREAD

**Issue by giyeonkwon** [entrylabs/entry-offline#166]
안녕하세요. 
clone 후 `yarn install` 에서 에러가 나서 문의 드립니다.
`error /Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native: Command failed.`

혹시나해서 `yarn.lock`을 지우고 `yarn install`을 해도 같은 에러가 발생됩니다.

System Version: macOS 12.3 (21E230)
Kernel Version: Darwin 21.4.0
Chip: Apple M1 Pro
node version: v16.14.2
yarn version: v1.22.19

```
yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "literallycanvas-mobile > browserify-shim@3.8.14" has unmet peer dependency "browserify@>= 2.3".
warning " > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "@typescript-eslint/parser@^2.0.0".
warning " > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] 🔨  Building fresh packages...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
error /Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build && rimraf build
Arguments:
Directory: /Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@16.14.2 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" (not found)
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.14.2 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.14.2 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
(node:67034) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/giyeonkwon/Library/Caches/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/giyeonkwon/Library/Caches/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/giyeonkwon/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.14.2 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/giyeonkwon/.nvm/versions/node/v16.14.2/bin/node" "/Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/giyeonkwon/.nvm/versions/node/v16.14.2/bin/node /Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node --module_name=lzma_native --module_path=/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/giyeonkwon/entry/entry-offline/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.4.0
node-pre-gyp ERR! command "/Users/giyeonkwon/.nvm/versions/node/v16.14.2/bin/node" "/Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/giyeonkwon/entry/entry-offline/node_modules/lzma-native
node-pre-gyp ERR! node -v v16.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/giyeonkwon/.nvm/versions/node/v16.14.2/bin/node /Users/giyeonkwon/entry/entry-offline/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/giyeonkwon/entry/ent
```

**Comment by giyeonkwon** [comment]
다른 기기에서는 `yarn install` 정상적으로 되는것을 확인했습니다.

System Version: macOS 10.13.6 (17G14033)
Kernel Version: Darwin 17.7.0
Processor Name: Intel Core i8
node version: v16.14.2
yarn version: v1.22.19

**Comment by giyeonkwon** [comment]
electron-rebuild 패키지의 문제가 있는것으로 보입니다.

OS: macOS 12.3
CPU: arm64 Apple M1 Pro

electron-rebuild v2.3.5 ❌ 설치안됨
electron-rebuild v3.0.0 ✅ 설치됨

https://github.com/electron/rebuild/compare/v2.3.5...v3.0.0

**Comment by Tnks2U** [comment]
@giyeonkwon 
제보 감사합니다.
곧 offline의 electron 버전업이 있을 예정이니 변경된 버전으로 설치테스트 해보시는것을 권장 드립니다.

**Comment by giyeonkwon** [comment]
@Tnks2U 
네 감사합니다.
