### ISSUE TITLE
WIN32 build 후 생성된 결과물 앱의 실행 불가 

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#198]
[빌드환경]
- Branch: clone from master branch (금일자 기준)
- OS: Windows 10
- node version: 16.20.2
- npm version: 8.19.4
- node-gyp version: 9.4.0
- MS Build: VS 2022

[증상]
- yarn webpack:dev 로 dev build 후 실행에 전혀 문제가 없음
- yarn dist:win32 로 prod build 하면, build는 아래의 로그처럼 prebuilt된 바이너리를 다운로드 할 수 없어 에러가 나긴 하지만, electron rebuild의 local source build 한 바이너리를 대신 사용하므로, 최종적으로는 빌드는 성공된 종결로 간주되는 것으로 여겨지며, 최종 빌드결과물까지 잘 생성됨. (참고로 생성된 app.asar 파일 안에 node_modules에서 serialport와 node-hid 안에 빌드된 바이너리가 존재함을 확인했음)
```
rebuilding native dependencies  dependencies=@serialport/bindings@9.2.9, node-hid@2.1.1 platform=win32 arch=ia32
  • install prebuilt binary  name=@serialport/bindings version=9.2.9 platform=win32 arch=ia32 napi=
  • build native dependency from sources  name=@serialport/bindings
                                          version=9.2.9
                                          platform=win32
                                          arch=ia32
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=c:\dev\entry-offline\node_modules\prebuild-install\node_modules\node-abi\index.js:36
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 18.3.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (c:\dev\entry-offline\node_modules\prebuild-install\node_modules\node-abi\index.js:36:9)
        at module.exports (c:\dev\entry-offline\node_modules\prebuild-install\rc.js:52:57)
        at Object.<anonymous> (c:\dev\entry-offline\node_modules\prebuild-install\bin.js:8:25)
        at Module._compile (node:internal/modules/cjs/loader:1198:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
        at Module.load (node:internal/modules/cjs/loader:1076:32)
        at Function.Module._load (node:internal/modules/cjs/loader:911:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:22:47

  • install prebuilt binary  name=node-hid version=2.1.1 platform=win32 arch=ia32 napi=
  • build native dependency from sources  name=node-hid
                                          version=2.1.1
                                          platform=win32
                                          arch=ia32
                                          napi=
reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 6.1.4
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds\node-hid-v2.1.1-napi-v3-win32-ia32.tar.gz
    prebuild-install info looking for cached prebuild @ C:\Users\JJ\AppData\Roaming\npm-cache\_prebuilds\c6aacd-node-hid-v2.1.1-napi-v3-win32-ia32.tar.gz
    prebuild-install http request GET https://github.com/node-hid/node-hid/releases/download/v2.1.1/node-hid-v2.1.1-napi-v3-win32-ia32.tar.gz
    prebuild-install http 404 https://github.com/node-hid/node-hid/releases/download/v2.1.1/node-hid-v2.1.1-napi-v3-win32-ia32.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=ia32 libc= platform=win32)

  • rebuilding native dependency  name=@serialport/bindings version=9.2.9
  • rebuilding native dependency  name=node-hid version=2.1.1
  • packaging       platform=win32 arch=ia32 electron=18.3.0 appOutDir=dist\Entry-win32-ia32\win-ia32-unpacked
  • app.asar checksum: 24d6394301e57899c4de8ed7546428e2be82b57e
Done in 94.34s.
```
이후에 dist 디렉토리 안에 생성된 빌드 결과물에서 Entry.exe를 실행시, 아래와 같은 로그를 출력하며 회색화면 뜬 상태로 멈춰있는 증상이 나타남.

```
[ParseCommandLine][info][2024-03-20 02:28:09]: commandLine configurations applied
version: 2.1.12
[ConfigInitialize][info][2024-03-20 02:28:09]: load c:\dev\entry-offline\dist\Entry-win32-ia32\win-ia32-unpacked\resources\app.asar\config\config.ko.json...
[ConfigInitialize][info][2024-03-20 02:28:09]: config file configurations applied
updateCheckUrl: https://playentry.org/api/checkVersion
moduleResourceUrl: http://localhost:23518/modules
remoteModuleResourceUrl: https://playentry.org/modules
(node:21164) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "c:\dev\entry-offline\dist\Entry-win32-ia32\win-ia32-unpacked\resources\app.asar\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe", "c:\dev\entry-offline\dist\Entry-win32-ia32\win-ia32-unpacked\resources\app.asar\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe" and "c:\dev\entry-offline\dist\Entry-win32-ia32\win-ia32-unpacked\resources\app.asar\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe"
(Use `Entry --trace-warnings ...` to show where the warning was created)
(node:21164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[main/mainWindowManager][verbose][2024-03-20 02:28:10]: mainWindow created
[main/aboutWindowManager.ts][verbose][2024-03-20 02:28:10]: about window created
WebContents #1 called ipcRenderer.sendSync() with 'REMOTE_BROWSER_GET_BUILTIN' channel without listeners.
WebContents #2 called ipcRenderer.sendSync() with 'REMOTE_BROWSER_GET_BUILTIN' channel without listeners.
```

**Comment by Tnks2U** [comment]
제보 감사합니다.
확인해 보겠습니다.

**Comment by Tnks2U** [comment]
이 이슈는 최근 소리편집 기능을 위해 추가한 라이브러리인 ffmpeg의 win32버전 빌드가 포함되지 않아 발생한 문제로 확인되었습니다.
현재 32비트 윈도우에 대한 지원 중단을 고려중이어서 정책이 확정되면 대응할 예정입니다.

**Comment by JeongJun-Lee** [comment]
이유를 정확히 몰라 원인을 찾는다고 무척(?) 고생했는데 감사합니다. 주신 힌트를 바탕으로 ffmpeg / ffprobe 32비트 버전을 의도적으로 탑재하여 ia32 빌드를 해보니 정상동작하더군요. 저희는 당분간 이런식으로 대응하면 될 것 같습니다.
