### ISSUE TITLE
ERROR in ./src/main.js     Module build failed (from ./node_modules/babel-loader/lib/index.js):     Error: Cannot find module 'core-js/modules/es6.weak-set'

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#82]
윈도우즈에서 2.0.2 소스코드 받고, dependancy 를 다 설치후 아래와 같이 빌드하면 바로 에러가 납니다. 참고로 맥에서는 문제없이 잘 빌드됩니다.

C:\Users\JJ\dev\entry\entry-offline>npm run webpack:dev

> entry@2.0.2 webpack:dev C:\Users\JJ\dev\entry\entry-offline
> cross-env NODE_ENV=development webpack

Hash: c1ee4653443131fba980759819ca5e519cdf1515
Version: webpack 4.29.6
Child
    Hash: c1ee4653443131fba980
    Time: 422ms
    Built at: 2019-03-28 01:27:13
                 Asset      Size  Chunks             Chunk Names
        main.bundle.js  30.6 KiB    main  [emitted]  main
    main.bundle.js.map  28.7 KiB    main  [emitted]  main
    Entrypoint main = main.bundle.js main.bundle.js.map
    [./src/main.js] 3.05 KiB {main} [built] [failed] [1 error]

    ERROR in ./src/main.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module 'core-js/modules/es6.weak-set'
        at Function.Module._resolveFilename (module.js:536:15)
        at Function.Module._load (module.js:466:25)
        at Module.require (module.js:579:17)
        at require (C:\Users\JJ\dev\entry\entry-offline\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at Object.<anonymous> (C:\Users\JJ\dev\entry\entry-offline\node_modules\babel-plugin-async-import\dist\index.js:8:1)
        at Module._compile (C:\Users\JJ\dev\entry\entry-offline\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)
        at Function.Module._load (module.js:489:3)
        at Module.require (module.js:579:17)
        at require (C:\Users\JJ\dev\entry\entry-offline\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at requireModule (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\files\plugins.js:165:12)
        at loadPlugin (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\files\plugins.js:68:17)
        at createDescriptor (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
        at items.map (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
        at Array.map (<anonymous>)
        at createDescriptors (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
        at createPluginDescriptors (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-descriptors.js:105:10)
        at plugins (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-descriptors.js:40:19)
        at mergeChainOpts (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-chain.js:319:26)
        at C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-chain.js:283:7
        at buildRootChain (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\config-chain.js:120:22)
        at loadPrivatePartialConfig (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\partial.js:85:55)
        at Object.loadPartialConfig (C:\Users\JJ\dev\entry\entry-offline\node_modules\@babel\core\lib\config\partial.js:110:18)
        at Object.<anonymous> (C:\Users\JJ\dev\entry\entry-offline\node_modules\babel-loader\lib\index.js:140:26)
        at Generator.next (<anonymous>)
        at asyncGeneratorStep (C:\Users\JJ\dev\entry\entry-offline\node_modules\babel-loader\lib\index.js:3:103)
        at _next (C:\Users\JJ\dev\entry\entry-offline\node_modules\babel-loader\lib\index.js:5:194)
        at C:\Users\JJ\dev\entry\entry-offline\node_modules\babel-loader\lib\index.js:5:364

**Comment by extracold1209** [comment]
@JeongJun-Lee 
core-js 에서 해당 모듈을 찾을 수 없다는 에러인데요.
node_modules 삭제 및 yarn.lock(혹은 package-lock.json) 을 삭제 한 후 다시 시도해보시기 바랍니다.

충돌 및 문제가 되는 디펜던시는 찾아서 수정하도록 하겠습니다.

**Comment by JeongJun-Lee** [comment]
혹시 윈도우즈 머신에서 clean 상태에서 소스코드 받고, 디펜던시 설치하고 빌드 테스트 해보셨는지요? 전 증상이 동일해서요.

2019년 3월 28일 (목) 오전 7:07, ExtraCold <notifications@github.com>님이 작성:

**Comment by JeongJun-Lee** [comment]
혹시 윈도우즈 머신에서 clean 상태에서 소스코드 받고, 디펜던시 설치하고 빌드 테스트 해보셨는지요? 전 증상이 동일해서요.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

네 윈도우즈 머신에서 git clone 으로 작업해보았는데 잘 되었습니다.
저희도 내부 빌드중에 한번 발생한 오류였어서 yarn.lock 혹은 기존 node_modules 를 몇번 수정하면서 에러가 다시 발생하지 않게되었는데요.

현재 babel-plugin-transform-async-to-generator 와 jszip 에서 core-js 에 디펜던시가 걸려있어 이쪽을 확인해볼 예정입니다.

**Comment by JeongJun-Lee** [comment]
npm 말고 yarn으로 하면 에러가 안납니다. 맥에서는 npm으로도 잘됩니다. 참고하세요.

**Comment by extracold1209** [comment]
6cb8ecac806eb96bcb8a4476d3e65f264dd7bbef 반영 이후 확인 필요한 이슈입니다.
